spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://poppool-prod-db.cpgg2ekawa60.ap-northeast-2.rds.amazonaws.com:3306/poppool?serverTimezone=Asia/Seoul
    username: poppool
    password: poppool123!

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


